apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 3  # Number of replicas (pods) you want to run
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: devopsproject1.azurecr.io/devopsproject1:latest  # ACR image URL
          ports:
            - containerPort: 3000
