name: CI/CD to Azure Kubernetes Service (AKS)

on:
  push:
    branches:
      - main  # Change if your main branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Set Azure Subscription (to avoid "No subscriptions found" error)
      - name: Set Azure Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 4: Login to Azure Container Registry (ACR)
      - name: Login to ACR
        run: |
          az acr login --name devopsproject1

      # Step 5: Build and Push Docker Image to ACR
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=devopsproject1.azurecr.io/devopsproject1:${{ github.sha }}
          docker build -t $IMAGE_TAG -f frontend/Dockerfile frontend/
          docker push $IMAGE_TAG

      # Step 6: Set up kubectl for AKS
      - name: Set up AKS credentials
        run: |
          az aks get-credentials --resource-group Devopsproject --name nodejsfrontend

      # Step 7: Deploy to AKS using deployment.yaml and service.yaml
      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl set image deployment/nodejs-app nodejs-app=devopsproject1.azurecr.io/devopsproject1:${{ github.sha }} -n default
          kubectl rollout status deployment/nodejs-app -n default

      # Step 8: Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl get pods -n default
