- name: Azure Login
  uses: azure/login@v1
  with:
    creds: ${{ secrets.AZURE_CREDENTIALS }}

- name: Set Azure Subscription
  run: |
    az account set --subscription 0bf4f1cc-f329-4a3f-af6c-37912b5a5e54

- name: Verify Azure Account
  run: |
    az account show
